INFO     root:data_depend.py:37 提取变量：errorFileId: cfa0bc35-4558-47ba-9ed8-958e4c3f0f2f
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!