INFO     root:data_depend.py:37 提取变量：errorFileId: 6a6b311a-0ecc-40d9-b667-d7d2f9a3d938
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!